version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    allow:
      # Allow only production updates for Sphinx
      - dependency-name: sphinx
        dependency-type: production
    groups:
      pip:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: monthly
    groups:
      workflows:
        patterns:
          - '*'
